name: Fetch Emails

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script with secrets
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: |
          echo "EMAIL_USER is set to: $EMAIL_USER"
          if [ -z "$EMAIL_USER" ]; then echo "❌ EMAIL_USER is missing!"; exit 1; fi
          if [ -z "$EMAIL_PASS" ]; then echo "❌ EMAIL_PASS is missing!"; exit 1; fi
          python fetch_emails.py
